title: " "
description: "Power Systems PhD Student | Energy Storage | Carbon Signals | Optimization"
url: "https://ALESNIAK3.github.io"
baseurl: ""  # keep empty for user sites

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default" # try "air", "mint", "dark", etc.
author_profile: true

# Turn off follow button + follower counts in the sidebar
show_follow: false
minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      show_author_profile: true
      show_follow: false

author: "default"

# author:
#   name: "Angelina Lesniak"
#   email: "alesniak2@wisc.edu"
#   links:
#     - label: "Google Scholar"
#       icon: "fas fa-graduation-cap"
#       url: "https://scholar.google.com/citations?user=NYCFfKQAAAAJ&hl=en&oi=ao"
#     - label: "GitHub"
#       icon: "fab fa-github"
#       url: "https://github.com/YOURUSERNAME"
#     - label: "LinkedIn"
#       icon: "fab fa-linkedin"
#       url: "www.linkedin.com/in/angelina-l-315033282"
